# Generated by Django 2.1.2 on 2019-10-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innbetalinger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restgjeld', models.FloatField(default=0)),
                ('dato', models.DateField()),
                ('gjeldsbetaling', models.FloatField(default=0)),
                ('gebyr', models.FloatField(default=0)),
                ('renter', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Laan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laanebelop', models.FloatField(default=0)),
                ('nominellRente', models.FloatField(default=0)),
                ('terminGebyr', models.FloatField(default=0)),
                ('utlopsDato', models.DateField()),
                ('saldoDato', models.DateField()),
                ('datoForsteInnbetaling', models.DateField()),
            ],
        ),
    ]
