# Generated by Django 2.1.2 on 2019-10-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_innbetalinger_laan'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Innbetalinger',
            new_name='Innbetaling',
        ),
    ]
